### ISSUE TITLE
p1v3 full option

### ISSUE THREAD

**Issue by mvieleers** [plugwise/Plugwise-Smile#23]
Following up on the conversation here: https://community.home-assistant.io/t/plugwise-smile-p1-integration-dsmr4-slimme-meter/47404/11?u=mvieleers

Attached are the xml files. I hope I did a good job on removing the personal details. I only found some stuff in domain_objects not in other files.

With the current implementation I get the following info:
sensor.smile_p1_electricity_consumed_peak_cumulative
sensor.smile_p1_electricity_consumed_peak_point
sensor.smile_p1_electricity_produced_peak_cumulative
sensor.smile_p1_electricity_produced_peak_point
sensor.smile_p1_net_electricity_cumulative
sensor.smile_p1_net_electricity_point

What I meant with that I see fields missing, has to do with the fact that my plugwise app shows me two fields for production (high and low rate). Same applies to consumption (Verbruik). Current entitites in Home Asssitant only show the high rates and do not report the low rates.

Also I have a gasmeter reported on, that entity is not shown in Home Assistant.

Gratefull for any additions you're able to do.

Let me know if something else is needed.
![IMG_14D99A4FC6F4-1](https://user-images.githubusercontent.com/10944296/78785168-ee6eeb00-79a6-11ea-8685-f801e11ab552.jpeg)
[p1v3_full_option.zip](https://github.com/plugwise/Plugwise-Smile/files/4450485/p1v3_full_option.zip)

**Comment by CoMPaTech** [comment]
Hi Marc,

Thanks, will include the files and run some tests against them, it should provide that information though so I'm curious to check your files. The no solar/gas one reports multi-tariff but maybe detection goes wrong.

i.e. ```{'name': 'Smile P1', 'types': {'home', 'power'}, 'class': 'gateway', ... data: {'electricity_consumed_peak_point': 644.0, 'electricity_consumed_off_peak_point': 0.0, ...``` (from [Travis](https://travis-ci.org/github/plugwise/Plugwise-Smile) about line 622 or thereabout. What I did is try detecting multi-tariff but apparently that needs improvement :)

**Comment by CoMPaTech** [comment]
Hi @mvieleers can you check your settings in the app? The xml reports `<electricity_consumption_tariff_structure>single</electricity_consumption_tariff_structure>`, not sure why it still sets peak and offpeak then.

**Comment by mvieleers** [comment]
The app settings don't reveal much. It shows my smile_id, I can change the name of my device, it has the firmware version (3.3.9) and I can go to the html interface.
No settings to set rate structure.

My energy provider has an app where I can set my rate to either use single rate or dual rate (high/low). 
Although my rate is set to single, my energy meter is measuring the consumption (and production) per rate time block. That's why I guess the smile shows the same. The single rate only has an effect on the invoice, as it has the same rate for both the high and low. Hope this makes sense.

**Comment by CoMPaTech** [comment]
Just checking mine (also 339 now) but seems the app won't let you into the HTML interface remotely (makes sense). We'll drop the tariff detection and will just show all values, hold on

**Comment by CoMPaTech** [comment]
Power functional, now up for gas

**Comment by mvieleers** [comment]
What should I do to get the new power features in?
Have updated to 0.1.8, but don't see a change yet. Maybe I'm too eager ;-)

**Comment by CoMPaTech** [comment]
Still working on it ... somehow gas works on smile p1 v2 but not on v3. Was trying to get that working as well 📦

**Comment by CoMPaTech** [comment]
It's going to take some more debugging I fear, for some reason v2's report gas but our v3's dont.

**Comment by mvieleers** [comment]
no rush, mate!  Just grateful somebody is creating all these integrations.
Let me know if you want me to test something.

**Comment by CoMPaTech** [comment]
Probably fixed by doing less and stating unablement to find it ... requires some review from @bouwew though just to be sure

**Comment by CoMPaTech** [comment]
Apologies for the delay :) 
Very keen to see if this improves your P1 experience!

**Comment by CoMPaTech** [comment]
@mvieleers version 0.1.11 :)

**Comment by mvieleers** [comment]
Brilliant! All electricity values are now visible. Gas is not showing though. Are extra steps needed apart from updating the integration?

**Comment by CoMPaTech** [comment]
They shouldn't ... from our testsuite I'd presume them to be there, let me check the component

**Comment by CoMPaTech** [comment]
Again apologies mate, on me ... didn't update the component, wait one

**Comment by CoMPaTech** [comment]
Released it as 0.1.11p1 for now

**Comment by mvieleers** [comment]
You nailed it! Also gas is showing now. Thank you so much. Love it! Much appreciated!

**Comment by CoMPaTech** [comment]
Thanks for the feedback and sharing your data, communityspirit!

**Comment by mvieleers** [comment]
Started with the Home Assistant project a few days ok. Finding the community extremely helpful so far.
It has got a lot of potential, with a lot more flexibility then my previous project on the Homey.
