### ISSUE TITLE
Problems after firmware update 4.0.15

### ISSUE THREAD

**Issue by wburgers** [plugwise/Plugwise-Smile#6]
Hi guys,

As mentioned on the forums (https://community.home-assistant.io/t/advice-how-to-load-sensor-info-from-plugwise-anna-thermostat-web-interface-xml/87801/219?u=wburgers), my Anna was updated to a newer firmware by plugwise.
Here are my XML files for you to get this latest firmware to work as well.

Keep up the great work!
Thanks!
[Anna.zip](https://github.com/plugwise/Plugwise-Smile/files/4419794/Anna.zip)

**Comment by CoMPaTech** [comment]
Thanks for the files! Version 0.51 is the one to look for when HACS-ing
