### ISSUE TITLE
[FEATURE] Code redundancy / FW4 changes

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/Plugwise-Smile#63]
**Is your feature request related to a problem? Please describe.**
Code improvement after firmware update (Anna v4 - Adam to be investigate).
From https://github.com/plugwise/plugwise-beta/issues/61

**Describe the solution you'd like**
Decision needs to be made towards relevance for switching schema in HA. Currently `climate` core doesn't seem to support a service (and therefore) nor frontend ability besides tinkering with the preset changing (which we shouldn't replace, preset changing is a valued end-user frontend (and service) change).

Pending that decision either/or:

 - [ ] Drop schema displaying (note: there is no schema handling at this time besides on/off)
 - [ ] We modify the current code to handle finding/displaying schema's better
 - [ ] Should handle loss of location (at least on Anna) when user switches schema
 - [ ] Add custom service (without frontend, although `input_select` might be an idea)

**Describe alternatives you've considered**

**Home Assistant (please complete the following information):**
 - Version: 0.109+
 - Deployment: hassos
 - Installed plugwise version: plugwise-beta
 - Installed through HACS

**Smile (please complete the following information):**
 - Sort of Smile: Anna (but might apply to Adam)
 - Firmware: 4.0.15
 - Setup: no auxiliary or additionals

**Additional context**
Tested (on Anna) - you can still disable a schema using HA/this module - which does set `active=False`. The same from the HTML-interface. Switching schema's has both remaing `active=True`

**Comment by CoMPaTech** [comment]
Note that pending outcome our code should be modified as https://github.com/plugwise/Plugwise-Smile/blob/92b899ae06c2a7c7acbd9e58c9e3e2cb89ae693f/Plugwise_Smile/Smile.py#L935 isn't per say valid in v4 firmware. It works because v4 unsets `locations` - not because the activeness is withdrawn by setting `active` to False.

**Comment by bouwew** [comment]
Solved by PR #67.
