### ISSUE TITLE
Support for Stretch possible?

### ISSUE THREAD

**Issue by joepvanboekel** [plugwise/Plugwise-Smile#81]
Any chance I could Use this also for the old Plugwise Stretch ?

In HA it gets recognized, but gives an error when entering the 8 characters: ‘ Ongeldige authenticatie, controleer de 8 karakters van uw Smile-ID’ 

I Think this is to start with the fact that the stretch Wants the username ‘stretch’ when logging in

I CAn visit this page which I read somewhere contains information needed: http://192.168.1.8/core/domain_objects

A snippet from that page:
Wasdroger 043AECA dryer 2014-04-05T01:09:44.235+02:00 2020-07-30T07:58:15.458+02:00 2020-07-30T07:58:14.206+02:00 electricity_consumed Wh 2020-07-30T06:00:00+02:00 PT1H 0.00 2020-07-30T07:58:14.177+02:00 electricity_produced W 2014-04-05T02:03:17.416+02:00 0.00 electricity_produced Wh PT1H 2020-07-30T07:58:14.177+02:00 electricity_consumed W 2020-07-28T10:08:07.206+02:00 1.31 2020-07-30T07:58:15.427+02:00 relay 2019-05-10T21:19:52.022+02:00 on 2020-07-30T07:58:15.458+02:00 on true printer 2015-05-26T19:41:31.087+02:00 2019-04-29T22:18:45.364+02:00 Plugwise NR 0000-0440-0107 2011-06-27T10:52:18+02:00 2014-04-05T01:05:07.112+02:00 2020-07-30T07:58:22.394+02:00 0.00 0.00 0.00 off

**Comment by CoMPaTech** [comment]
Is this related / see also recent messages on https://community.home-assistant.io/t/plugwise-smile-custom-component-beta/183560/98

**Comment by bouwew** [comment]
Supported added in v1.4.0
And in Plugwise-beta v0.7.0/0.8.0
