### ISSUE TITLE
Conflicting setup requirement with standard library for Python 3.7 / 3.8

### ISSUE THREAD

**Issue by MartinHjelmare** [plugwise/Plugwise-Smile#86]
**Describe the bug**
- This library supports an integration in Home Assistant.
- One or more of the requirements of this library (see below) conflicts with one or more standard library modules for Python 3.7 and/or 3.8.
- To avoid issues it would be good if this library would remove these conflicting requirements from your library setup requirements or use a condition to only install the requirements when using a lower Python version.
- If a `setup.py` file is used it means updating the `install_requires` list and removing or updating the conflicting requirements.
  - See this blog for how to use a condition in `install_requires`: https://hynek.me/articles/conditional-python-dependencies/
- Found conflicts:
  - `asyncio`
  - `datetime`

**Evidence**
```
(home-assistant) x:~/Dev/home-assistant/home-assistant$ pipdeptree -w silence --packages Plugwise-Smile
Plugwise-Smile==1.1.0
...
  - asyncio [required: Any, installed: 3.4.3]
  - datetime [required: Any, installed: 4.3]
    - pytz [required: Any, installed: 2020.1]
    - zope.interface [required: Any, installed: 5.1.0]
      - setuptools [required: Any, installed: 46.1.3]
...
```

**Expected behavior**
Modules that are already available in the standard library should not be installed from PyPI to avoid conflicts.

**Home Assistant Core (please complete the following information):**
 - Version: 0.115.0.dev0
 - Deployment: venv
 - Installed plugwise version: HA-core
 - Installed through Core

**Comment by bouwew** [comment]
@MartinHjelmare Noted, thanks!

Does this have a higher priority than the open PR's? Meaning, should we fix this before these PR's are getting merging?

**Comment by MartinHjelmare** [comment]
This can be fixed separately, but it's probably a small change, so can be done quickly. I'm assuming you don't need the zope interface that the DateTime library on PyPI is using.

https://pypi.org/project/DateTime/

**Comment by CoMPaTech** [comment]
> This can be fixed separately, but it's probably a small change, so can be done quickly. I'm assuming you don't need the zope interface that the DateTime library on PyPI is using.
> 
> https://pypi.org/project/DateTime/

Nope, rather without zope, thanks for pointing that out.

**Comment by CoMPaTech** [comment]
Not yet closed, still in beta-release waiting for release minor

**Comment by CoMPaTech** [comment]
@MartinHjelmare tested against `dev` just yet as well as for both open PRs from our side - looks like `1.3.0b13` is acceptable for HA but we are expecting results from our testers environments to be sure.

**Comment by CoMPaTech** [comment]
@MartinHjelmare home-assistant/core#39726 is merged, can you verify / can we close this one as well?

**Comment by MartinHjelmare** [comment]
Yes. Thanks!
